"""initial

Revision ID: e89cb1a3017d
Revises:
Create Date: 2026-09-30 10:46:44.975712

"""

from alembic import op
import sqlalchemy as sa


revision = "e89cb1a3017d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patient_demog",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sendingfacility", sa.String(length=7), nullable=False),
        sa.Column("nationalid", sa.String(length=50), nullable=False),
        sa.Column("numbertype", sa.String(length=3), nullable=False),
        sa.Column("organization", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sendingfacility", "nationalid", "numbertype", "organization"
        ),
    )
    op.create_index(
        op.f("ix_patient_demog_nationalid"),
        "patient_demog",
        ["nationalid"],
        unique=False,
    )
    op.create_table(
        "patientnumbersubstitute",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ukrdc_patientid", sa.String(length=50), nullable=True),
        sa.Column("ukrdc_organisation", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assessment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("patientid", sa.Integer(), nullable=True),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_date", sa.DateTime(), nullable=True),
        sa.Column("assessmentstart", sa.DateTime(), nullable=True),
        sa.Column("assessmentend", sa.DateTime(), nullable=True),
        sa.Column("assessmenttypecode", sa.String(length=100), nullable=True),
        sa.Column("assessmenttypecodestd", sa.String(length=100), nullable=True),
        sa.Column("assessmenttypecodedesc", sa.String(length=100), nullable=True),
        sa.Column("assessmentoutcomecode", sa.String(length=100), nullable=True),
        sa.Column("assessmentoutcomecodestd", sa.String(length=100), nullable=True),
        sa.Column("assessmentoutcomecodedesc", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["patientid"], ["patient_demog.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "causeofdeath",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("patientid", sa.Integer(), nullable=True),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_date", sa.DateTime(), nullable=True),
        sa.Column("diagnosistype", sa.String(length=50), nullable=True),
        sa.Column("diagnosiscode", sa.String(length=100), nullable=True),
        sa.Column("diagnosiscodestd", sa.String(length=100), nullable=True),
        sa.Column("diagnosisdesc", sa.String(length=255), nullable=True),
        sa.Column("comments", sa.String(), nullable=True),
        sa.Column("verificationstatus", sa.String(), nullable=True),
        sa.Column("enteredon", sa.DateTime(), nullable=True),
        sa.Column("updatedon", sa.DateTime(), nullable=True),
        sa.Column("externalid", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["patientid"], ["patient_demog.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "diagnosis",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("patientid", sa.Integer(), nullable=True),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_date", sa.DateTime(), nullable=True),
        sa.Column("diagnosistype", sa.String(length=50), nullable=True),
        sa.Column("diagnosiscode", sa.String(), nullable=True),
        sa.Column("diagnosiscodestd", sa.String(), nullable=True),
        sa.Column("biopsyperformed", sa.String(), nullable=True),
        sa.Column("verificationstatus", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patientid"], ["patient_demog.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dialysisprescription",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("patientid", sa.Integer(), nullable=True),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_date", sa.DateTime(), nullable=True),
        sa.Column("enteredon", sa.DateTime(), nullable=True),
        sa.Column("fromtime", sa.DateTime(), nullable=True),
        sa.Column("totime", sa.DateTime(), nullable=True),
        sa.Column("sessiontype", sa.String(length=5), nullable=True),
        sa.Column("sessionsperweek", sa.Integer(), nullable=True),
        sa.Column("timedialysed", sa.Integer(), nullable=True),
        sa.Column("vascularaccess", sa.String(length=5), nullable=True),
        sa.ForeignKeyConstraint(
            ["patientid"], ["patient_demog.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "renaldiagnosis",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("patientid", sa.Integer(), nullable=True),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_date", sa.DateTime(), nullable=True),
        sa.Column("diagnosistype", sa.String(length=50), nullable=True),
        sa.Column("diagnosiscode", sa.String(), nullable=True),
        sa.Column("diagnosiscodestd", sa.String(), nullable=True),
        sa.Column("diagnosisdesc", sa.String(), nullable=True),
        sa.Column("diagnosingcliniciancode", sa.String(length=100), nullable=True),
        sa.Column("diagnosingcliniciancodestd", sa.String(length=100), nullable=True),
        sa.Column("diagnosingcliniciandesc", sa.String(length=100), nullable=True),
        sa.Column("biopsyperformed", sa.String(), nullable=True),
        sa.Column("comments", sa.String(), nullable=True),
        sa.Column("identificationtime", sa.DateTime(), nullable=True),
        sa.Column("onsettime", sa.DateTime(), nullable=True),
        sa.Column("verificationstatus", sa.String(), nullable=True),
        sa.Column("enteredon", sa.DateTime(), nullable=True),
        sa.Column("updatedon", sa.DateTime(), nullable=True),
        sa.Column("externalid", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["patientid"], ["patient_demog.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "treatment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("idx", sa.Integer(), nullable=True),
        sa.Column("patientid", sa.Integer(), nullable=True),
        sa.Column(
            "creation_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_date", sa.DateTime(), nullable=True),
        sa.Column("encounternumber", sa.String(length=100), nullable=True),
        sa.Column("encountertype", sa.String(length=100), nullable=True),
        sa.Column("fromtime", sa.DateTime(), nullable=True),
        sa.Column("totime", sa.DateTime(), nullable=True),
        sa.Column("admitreasoncode", sa.String(length=100), nullable=True),
        sa.Column("admitreasoncodestd", sa.String(length=100), nullable=True),
        sa.Column("admitreasondesc", sa.String(length=255), nullable=True),
        sa.Column("qbl05", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["patientid"], ["patient_demog.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("treatment")
    op.drop_table("renaldiagnosis")
    op.drop_table("dialysisprescription")
    op.drop_table("diagnosis")
    op.drop_table("causeofdeath")
    op.drop_table("assessment")
    op.drop_table("patientnumbersubstitute")
    op.drop_index(op.f("ix_patient_demog_nationalid"), table_name="patient_demog")
    op.drop_table("patient_demog")
    # ### end Alembic commands ###
