version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.8.1
  - dependency-name: sqlalchemy
    versions:
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.7
    - 1.4.8
    - 1.4.9
