"""initial

Revision ID: 64b09728f65b
Revises:
Create Date: 2026-09-30 10:44:31.714877

"""

from alembic import op
import sqlalchemy as sa


revision = "64b09728f65b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("personid", sa.Integer(), nullable=False),
        sa.Column("masterid", sa.Integer(), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("mainnationalid", sa.String(), nullable=True),
        sa.Column("mainnationalidtype", sa.String(), nullable=True),
        sa.Column("lastupdated", sa.DateTime(), nullable=False),
        sa.Column("updatedby", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "masterrecord",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lastupdated", sa.DateTime(), nullable=False),
        sa.Column("dateofbirth", sa.Date(), nullable=False),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("givenname", sa.String(), nullable=True),
        sa.Column("surname", sa.String(), nullable=True),
        sa.Column("nationalid", sa.String(), nullable=False),
        sa.Column("nationalidtype", sa.String(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("effectivedate", sa.DateTime(), nullable=False),
        sa.Column("creationdate", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("originator", sa.String(), nullable=False),
        sa.Column("localid", sa.String(), nullable=False),
        sa.Column("localidtype", sa.String(), nullable=False),
        sa.Column("nationalid", sa.String(), nullable=True),
        sa.Column("nationalidtype", sa.String(), nullable=True),
        sa.Column("dateofbirth", sa.Date(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("dateofdeath", sa.Date(), nullable=True),
        sa.Column("givenname", sa.String(), nullable=True),
        sa.Column("surname", sa.String(), nullable=True),
        sa.Column("prevsurname", sa.String(), nullable=True),
        sa.Column("othergivennames", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("postcode", sa.String(), nullable=True),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("stdsurname", sa.String(), nullable=True),
        sa.Column("stdprevsurname", sa.String(), nullable=True),
        sa.Column("stdgivenname", sa.String(), nullable=True),
        sa.Column("stdpostcode", sa.String(), nullable=True),
        sa.Column("skipduplicatecheck", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("localid"),
    )
    op.create_index(
        "ix_person_mrn", "person", ["originator", "localid", "localidtype"], unique=True
    )
    op.create_index("person_id_key", "person", ["id"], unique=True)
    op.create_table(
        "linkrecord",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("personid", sa.Integer(), nullable=False),
        sa.Column("masterid", sa.Integer(), nullable=False),
        sa.Column("linktype", sa.Integer(), nullable=False),
        sa.Column("linkcode", sa.Integer(), nullable=False),
        sa.Column("linkdesc", sa.String(), nullable=True),
        sa.Column("updatedby", sa.String(), nullable=True),
        sa.Column("lastupdated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["masterid"],
            ["masterrecord.id"],
        ),
        sa.ForeignKeyConstraint(
            ["personid"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pidxref",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pid", sa.String(), nullable=False),
        sa.Column("sendingfacility", sa.String(), nullable=False),
        sa.Column("sendingextract", sa.String(), nullable=False),
        sa.Column("localid", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pid"],
            ["person.localid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "pidxref_compound",
        "pidxref",
        ["sendingfacility", "sendingextract", "localid"],
        unique=True,
    )
    op.create_table(
        "workitem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("personid", sa.Integer(), nullable=False),
        sa.Column("masterid", sa.Integer(), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("creationdate", sa.DateTime(), nullable=True),
        sa.Column("lastupdated", sa.DateTime(), nullable=False),
        sa.Column("updatedby", sa.String(), nullable=True),
        sa.Column("updatedesc", sa.String(), nullable=True),
        sa.Column("attributes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["masterid"],
            ["masterrecord.id"],
        ),
        sa.ForeignKeyConstraint(
            ["personid"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workitem")
    op.drop_index("pidxref_compound", table_name="pidxref")
    op.drop_table("pidxref")
    op.drop_table("linkrecord")
    op.drop_index("person_id_key", table_name="person")
    op.drop_index("ix_person_mrn", table_name="person")
    op.drop_table("person")
    op.drop_table("masterrecord")
    op.drop_table("audit")
    # ### end Alembic commands ###
