"""Shared helpers for migrate.py, migrate_apply.py and migrate_csv.py.

Settings (flags or environment variables), the same for all three tools:
    --models / MIGRATE_MODELS       module:attr of the declarative Base (default: models:Base)
    --migrations / MIGRATE_DIR      folder holding versions/ (default: migrations)
    --db-url / MIGRATE_DB_URL       Postgres server to use instead of Docker
    --pg-image / MIGRATE_PG_IMAGE   Docker image (default: postgres:16; match production)
"""

from __future__ import annotations

import importlib
import importlib.util
import json
import re
import shutil
import subprocess
import sys
import time
import uuid
from contextlib import contextmanager, nullcontext
from pathlib import Path

import click
from alembic.operations import Operations
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from alembic.util import CommandError
from sqlalchemy import MetaData, create_engine
from sqlalchemy.engine import URL, make_url
from sqlalchemy.exc import DBAPIError, OperationalError

DOCKER_LABEL = "migrate.py=scratch"


# --------------------------------------------------------------------------- CLI plumbing

def make_cli(help_text: str) -> click.Group:
    """A click group with the settings every tool shares."""

    @click.group(help=help_text, context_settings={"max_content_width": 100})
    @click.option("--models", envvar="MIGRATE_MODELS", default="models:Base", show_default=True,
                  help="module:attr of the declarative Base (or a MetaData).")
    @click.option("--migrations", envvar="MIGRATE_DIR", default="migrations", show_default=True,
                  type=click.Path(file_okay=False, path_type=Path),
                  help="Folder containing versions/, sql/ and attributes/.")
    @click.option("--db-url", envvar="MIGRATE_DB_URL", default=None,
                  help="Postgres server to use for scratch databases (they're created and "
                       "dropped). Default: start one in Docker.")
    @click.option("--pg-image", envvar="MIGRATE_PG_IMAGE", default="postgres:16", show_default=True,
                  help="Docker image when no --db-url is given. Match your production version.")
    @click.pass_context
    def cli(ctx, models, migrations, db_url, pg_image):
        ctx.obj = {"models": models, "migrations": migrations, "db_url": db_url, "pg_image": pg_image}

    return cli


def run(cli: click.Group) -> None:
    """Run a tool's CLI with friendly errors."""
    try:
        cli(standalone_mode=False)
    except click.exceptions.Abort:
        sys.exit(1)
    except click.ClickException as e:
        e.show()
        sys.exit(e.exit_code)
    except CommandError as e:  # Alembic's errors, e.g. an unknown revision
        click.secho(f"Error: {e}", fg="red", err=True)
        sys.exit(1)
    except RuntimeError as e:
        if not is_review_error(e):
            raise
        click.secho(f"Error: {e}\nNothing was applied (the migration ran in a transaction).",
                    fg="red", err=True)
        sys.exit(1)


# --------------------------------------------------------------------------- review markers

REVIEW_RE = re.compile(r"^(#|--) REVIEW STATUS: (UNCHECKED|CHECKED)\b.*\n", re.M)


def review_header(comment: str) -> str:
    return (f"{comment} REVIEW STATUS: UNCHECKED - generated by migrate.py. "
            "Review this file, then change UNCHECKED to CHECKED.\n")


def review_status(path: Path) -> str | None:
    m = REVIEW_RE.search(path.read_text(encoding="utf-8"))
    return m.group(2) if m else None


def _without_marker(text: str) -> str:
    return REVIEW_RE.sub("", text, count=1)


def write_generated(path: Path, body: str, comment: str) -> str:
    """Write a generated file with an UNCHECKED marker.

    Returns "created", "updated", "unchanged", or "kept-checked" (the file on disk is
    marked CHECKED and differs; it is left alone so reviewed work is never lost).
    """
    if path.exists():
        old = path.read_text(encoding="utf-8")
        if _without_marker(old) == body:
            return "unchanged"
        if review_status(path) == "CHECKED":
            return "kept-checked"
        status = "updated"
    else:
        status = "created"
    path.parent.mkdir(parents=True, exist_ok=True)
    # always UTF-8: Python reads source as UTF-8, Windows' default (cp1252) would break it
    path.write_text(review_header(comment) + body, encoding="utf-8")
    return status


# --------------------------------------------------------------------------- models & scripts

SKIP_DIRS = {".git", ".venv", "venv", "env", "node_modules", "__pycache__", "build", "dist",
             "migrations", ".tox", ".mypy_cache", ".pytest_cache", "site-packages"}


def _find_bases(root: Path) -> list[str]:
    """Suggest module:Base targets by finding files that define a declarative base."""
    found = []
    for path in root.rglob("*.py"):
        rel = path.relative_to(root)
        if SKIP_DIRS & set(rel.parts) or path.name == Path(__file__).name:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for line in text.splitlines():
            stripped = line.strip()
            name = None
            if stripped.startswith("class ") and "DeclarativeBase" in stripped:
                name = stripped[6:].split("(")[0].strip()
            elif "declarative_base(" in stripped and "=" in stripped and not stripped.startswith(("#", "from", "import")):
                name = stripped.split("=")[0].strip().split(":")[0].strip()
            if name and name.isidentifier():
                parts = list(rel.with_suffix("").parts)
                if parts and parts[0] == "src":
                    parts = parts[1:]
                if parts and parts[-1] == "__init__":
                    parts = parts[:-1]
                found.append(f"{'.'.join(parts)}:{name}")
    return sorted(set(found))


def load_metadata(target: str) -> MetaData:
    module_name, _, attr = target.partition(":")
    cwd = Path.cwd()
    for p in (cwd / "src", cwd):  # support both flat and src/ layouts
        if p.is_dir() and str(p) not in sys.path:
            sys.path.insert(0, str(p))
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError as e:
        hint = ""
        candidates = _find_bases(cwd)
        if candidates:
            hint = "\n\nDeclarative bases found in this folder:\n" + "\n".join(
                f"  --models {c}" for c in candidates)
        raise click.ClickException(
            f"Can't import {module_name!r} for --models ({e}).\n"
            f"Run from your repo root and pass --models package.module:Base "
            f"(or set MIGRATE_MODELS).{hint}") from None
    try:
        obj = getattr(module, attr or "Base")
    except AttributeError:
        raise click.ClickException(f"{module_name} has no attribute {attr or 'Base'!r}") from None
    metadata = obj if isinstance(obj, MetaData) else getattr(obj, "metadata", None)
    if not isinstance(metadata, MetaData):
        raise click.ClickException(f"{target} is not a declarative Base or MetaData")
    metadata.info["migrate_base"] = obj  # for model attribute names (CSV headers)
    if not metadata.tables:
        # Carrying on would generate a migration that drops every table.
        raise click.ClickException(
            f"{target} has no tables registered. Importing the module that defines Base "
            "doesn't load models defined in other modules: point --models at a module that "
            "imports all your models (e.g. a models/__init__.py), using its Base.")
    return metadata


def script_directory(migrations: Path) -> ScriptDirectory:
    (migrations / "versions").mkdir(parents=True, exist_ok=True)
    return ScriptDirectory(str(migrations))


def revision_chain(script: ScriptDirectory) -> list:
    """Revisions from first to latest. Branches aren't supported (merge them first)."""
    heads = script.get_heads()
    if len(heads) > 1:
        raise click.ClickException(f"multiple heads {heads}; merge them first")
    revs = list(reversed(list(script.walk_revisions())))
    for r in revs:
        if isinstance(r.down_revision, (tuple, list)):
            raise click.ClickException(f"{r.revision} is a merge revision; not supported")
    return revs


def slugify(text: str) -> str:
    first = (text or "").strip().splitlines()[0] if (text or "").strip() else "revision"
    return "".join(c if c.isalnum() else "_" for c in first.lower())[:40].strip("_") or "revision"


def migration_context(conn, script: ScriptDirectory, metadata: MetaData,
                      dialect_name: str | None = None, **opts) -> MigrationContext:
    return MigrationContext.configure(
        connection=conn,
        dialect_name=dialect_name,
        opts={"script": script, "target_metadata": metadata, "compare_type": True,
              "compare_server_default": False, **opts},
    )


def run_migrations(conn, script: ScriptDirectory, metadata: MetaData, destination: str,
                   downgrade: bool = False, dialect_name: str | None = None, **opts) -> None:
    """Run migrations on `conn`, or with conn=None and as_sql=True, write them out as SQL."""

    def step(rev, _context):
        if downgrade:
            return script._downgrade_revs(destination, rev)
        return script._upgrade_revs(destination, rev)

    ctx = migration_context(conn, script, metadata, dialect_name=dialect_name,
                            fn=step, destination_rev=destination, **opts)
    # offline: wrap the SQL in BEGIN/COMMIT so a failed script changes nothing
    transaction = ctx.begin_transaction() if opts.get("as_sql") else nullcontext()
    with Operations.context(ctx), transaction:
        ctx.run_migrations()


# --------------------------------------------------------------------------- throwaway Postgres

def _pg_driver() -> str:
    for module, driver in (("psycopg", "postgresql+psycopg"), ("psycopg2", "postgresql+psycopg2")):
        if importlib.util.find_spec(module):
            return driver
    raise click.ClickException(
        "No Postgres driver installed: pip install \"psycopg[binary]\" (or psycopg2-binary)")


def _docker(*args: str, check: bool = True) -> str:
    res = subprocess.run(["docker", *args], capture_output=True, text=True)
    if check and res.returncode != 0:
        raise click.ClickException(f"docker {args[0]} failed: {res.stderr.strip() or res.stdout.strip()}")
    return res.stdout.strip()


def _wait_for(engine, timeout: float, alive=lambda: True) -> None:
    deadline = time.monotonic() + timeout
    while True:
        try:
            with engine.connect() as conn:
                conn.exec_driver_sql("select 1")
            return
        except OperationalError:
            if not alive():
                raise click.ClickException("The Postgres container stopped while starting.")
            if time.monotonic() > deadline:
                raise click.ClickException(f"Postgres wasn't ready after {timeout:.0f}s.")
            time.sleep(0.5)


@contextmanager
def docker_postgres(image: str, timeout: float = 90):
    if shutil.which("docker") is None:
        raise click.ClickException("Docker isn't installed (or not on PATH). Install it, "
                                   "or pass --db-url to use a Postgres server you already run.")
    driver = _pg_driver()
    name = f"migrate-py-{uuid.uuid4().hex[:10]}"
    click.echo(f"Starting {image} in Docker ({name})...", err=True)
    _docker("run", "-d", "--rm", "--name", name, "--label", DOCKER_LABEL,
            "-e", "POSTGRES_USER=migrate", "-e", "POSTGRES_PASSWORD=migrate",
            "-e", "POSTGRES_DB=migrate", "-p", "127.0.0.1::5432", image)
    engine = None
    try:
        port = None
        for _ in range(20):  # the port mapping can take a moment to appear
            out = _docker("port", name, "5432/tcp", check=False)
            if out:
                port = int(out.splitlines()[0].rsplit(":", 1)[1])
                break
            time.sleep(0.25)
        if port is None:
            raise click.ClickException(f"Couldn't find the port Docker gave {name}.")
        engine = create_engine(URL.create(driver, "migrate", "migrate", "127.0.0.1", port, "migrate"))

        def alive():
            return _docker("inspect", "-f", "{{.State.Running}}", name, check=False) == "true"

        _wait_for(engine, timeout, alive)
        yield engine
    finally:
        if engine is not None:
            engine.dispose()
        _docker("rm", "-f", name, check=False)
        click.echo(f"Removed container {name}.", err=True)


@contextmanager
def temporary_database(server_url: str):
    """A temporary database on an existing Postgres server, dropped afterwards."""
    base = make_url(server_url)
    if not base.drivername.startswith("postgresql"):
        raise click.ClickException("--db-url must be a Postgres URL (postgresql://...)")
    if base.drivername == "postgresql":
        base = base.set(drivername=_pg_driver())
    name = f"migrate_scratch_{uuid.uuid4().hex[:10]}"
    shown = base.render_as_string(hide_password=True)
    admin = create_engine(base, isolation_level="AUTOCOMMIT")
    try:
        conn = admin.connect()
    except DBAPIError as e:
        admin.dispose()
        raise click.ClickException(
            f"Couldn't connect to {shown}: {str(e.orig).strip()}\n"
            "Is the server running? Or leave out --db-url to use Docker.") from None
    try:
        with conn:
            conn.exec_driver_sql(f'CREATE DATABASE "{name}"')
    except DBAPIError as e:
        admin.dispose()
        raise click.ClickException(
            f"Couldn't create a temporary database on {shown}: {str(e.orig).strip()}\n"
            "The user needs the CREATEDB permission. Or leave out --db-url to use Docker.") from None
    click.echo(f"Using temporary database {name} on {shown}.", err=True)
    engine = create_engine(base.set(database=name))
    try:
        yield engine
    finally:
        engine.dispose()
        with admin.connect() as conn:
            try:
                conn.exec_driver_sql(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)')
            except DBAPIError:  # Postgres < 13 has no FORCE
                conn.exec_driver_sql(f'DROP DATABASE IF EXISTS "{name}"')
        admin.dispose()
        click.echo(f"Dropped temporary database {name}.", err=True)


def scratch_postgres(obj):
    return temporary_database(obj["db_url"]) if obj["db_url"] else docker_postgres(obj["pg_image"])


# --------------------------------------------------------------------------- review blocks

REVIEW_NEEDED = "REVIEW NEEDED"


class ReviewPending(click.ClickException):
    """A revision still contains a review block (it raises when run)."""


def _shown(path) -> str:
    try:
        return str(Path(path).resolve().relative_to(Path.cwd().resolve()))
    except ValueError:
        return str(path)


def files_with_review_blocks(migrations: Path) -> list[str]:
    return [_shown(p) for p in sorted((migrations / "versions").glob("*.py"))
            if re.search(rf"raise RuntimeError\(['\"]{REVIEW_NEEDED}", p.read_text(encoding="utf-8"))]


def is_review_error(e: BaseException) -> bool:
    return isinstance(e, RuntimeError) and str(e).startswith(REVIEW_NEEDED)


# --------------------------------------------------------------------------- SQL files

def sql_path(migrations: Path, dialect: str, index: int, rev, kind: str) -> Path:
    return (migrations / "sql" / dialect
            / f"{index:04d}_{rev.revision}_{slugify(rev.doc)}.{kind}.sql")


# --------------------------------------------------------------------------- model attributes / CSV headers
#
# CSV headers follow the models' Python attribute names, which can change without the
# database noticing (mapped_column("firstdataquarter") stays the same column even if the
# attribute becomes `firstdataquarters`). A snapshot of attribute names per database
# column lets generate spot those renames and record them in the revision as
# a comment. Each revision keeps its
# own copy of the attribute names (migrations/attributes/), so deleting a revision also
# deletes its copy and the baseline falls back to the previous revision.

ATTRIBUTES_DIR = "attributes"                       # migrations/attributes/NNNN_<rev>_<slug>.json
LEGACY_ATTRIBUTES_FILE = "model_attributes.json"    # older single snapshot; adopted if found


def model_attributes(metadata: MetaData) -> dict | None:
    """{table: {database column: attribute name}} for every mapped table, or None if
    --models points at a bare MetaData (no mapped classes, so no attribute names)."""
    registry = getattr(metadata.info.get("migrate_base"), "registry", None)
    if registry is None:
        return None
    tables: dict[str, dict[str, str]] = {}
    for mapper in registry.mappers:
        table = mapper.local_table
        if getattr(table, "name", None) is None:
            continue
        cols = tables.setdefault(table.name, {})
        for col in table.columns:
            try:
                cols.setdefault(col.name, mapper.get_property_by_column(col).key)
            except Exception:  # column not mapped to an attribute
                continue
    return {t: dict(sorted(c.items())) for t, c in sorted(tables.items())}


def attributes_path(migrations: Path, index: int, revision: str, doc: str | None) -> Path:
    return migrations / ATTRIBUTES_DIR / f"{index:04d}_{revision}_{slugify(doc)}.json"


def find_attributes_file(migrations: Path, revision: str) -> Path | None:
    found = sorted((migrations / ATTRIBUTES_DIR).glob(f"*_{revision}_*.json"))
    return found[0] if found else None


def read_attributes(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))["tables"]


def write_attributes(path: Path, revision: str, tables: dict) -> None:
    data = {"about": "Generated by migrate.py: the models' attribute name for each database column "
                     "at this revision. Used to detect attribute (CSV header) renames and to check "
                     "CSV headers. Written once; don't edit.",
            "revision": revision, "tables": tables}
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def revision_attributes(migrations: Path, chain) -> dict[str, dict]:
    """{revision id: tables} for every revision that has an attributes file."""
    out = {}
    for rev in chain:
        path = find_attributes_file(migrations, rev.revision)
        if path:
            out[rev.revision] = read_attributes(path)
    return out


def baseline_attributes(migrations: Path, chain) -> tuple[dict | None, str]:
    """The latest revision's attribute names: (tables, where they came from)."""
    if not chain:
        return None, "none"
    path = find_attributes_file(migrations, chain[-1].revision)
    if path:
        return read_attributes(path), "revision"
    legacy = migrations / LEGACY_ATTRIBUTES_FILE  # from before attributes were kept per revision
    if legacy.exists():
        return json.loads(legacy.read_text(encoding="utf-8"))["tables"], "legacy"
    return None, "none"


def adopt_legacy_snapshot(migrations: Path, chain, tables: dict) -> None:
    """Move an old single model_attributes.json into the latest revision's attributes file."""
    head = chain[-1]
    write_attributes(attributes_path(migrations, len(chain), head.revision, head.doc), head.revision, tables)
    (migrations / LEGACY_ATTRIBUTES_FILE).unlink(missing_ok=True)


def attribute_renames(snapshot: dict | None, current: dict | None) -> list[dict]:
    """Attributes whose database column is unchanged but whose name changed."""
    if not snapshot or not current:
        return []
    out = []
    for table, cols in current.items():
        for column, key in cols.items():
            before = snapshot.get(table, {}).get(column)
            if before is not None and before != key:
                out.append({"table": table, "old": before, "new": key})
    return out
