"""initial

Revision ID: c4474deee1aa
Revises:
Create Date: 2026-09-30 10:44:53.494849

"""

from alembic import op
import sqlalchemy as sa


revision = "c4474deee1aa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("direction", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("store_first_message", sa.Boolean(), nullable=False),
        sa.Column("store_last_message", sa.Boolean(), nullable=False),
        sa.Column("resolved_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["channels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "facilities",
        sa.Column("facility", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("facility"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("channel_id", sa.String(), nullable=True),
        sa.Column("received", sa.DateTime(), nullable=True),
        sa.Column("msg_status", sa.String(), nullable=True),
        sa.Column("connector_index", sa.Integer(), nullable=True),
        sa.Column("connector_name", sa.String(), nullable=True),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.Column("ni", sa.String(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("facility", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
    )
    op.create_index("messages_facility_idx", "messages", ["facility"], unique=False)
    op.create_index("messages_filename_idx", "messages", ["filename"], unique=False)
    op.create_index("messages_msg_status_idx", "messages", ["msg_status"], unique=False)
    op.create_index("messages_ni_idx", "messages", ["ni"], unique=False)
    op.create_index("messages_received_idx", "messages", ["received"], unique=False)
    op.create_table(
        "latests",
        sa.Column("ni", sa.String(), nullable=False),
        sa.Column("facility", sa.String(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("ni", "facility"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("latests")
    op.drop_index("messages_received_idx", table_name="messages")
    op.drop_index("messages_ni_idx", table_name="messages")
    op.drop_index("messages_msg_status_idx", table_name="messages")
    op.drop_index("messages_filename_idx", table_name="messages")
    op.drop_index("messages_facility_idx", table_name="messages")
    op.drop_table("messages")
    op.drop_table("facilities")
    op.drop_table("channels")
    # ### end Alembic commands ###
