"""initial

Revision ID: eb3a02bc0793
Revises:
Create Date: 2026-09-30 10:46:07.067881

"""

from alembic import op
import sqlalchemy as sa


revision = "eb3a02bc0793"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "error_history",
        sa.Column("facility", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("facility", "date"),
    )
    op.create_table(
        "last_run_times",
        sa.Column("table", sa.String(), nullable=False),
        sa.Column("facility", sa.String(), nullable=False),
        sa.Column("last_run_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("table", "facility"),
    )
    op.create_table(
        "multiple_ukrdcid",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("master_id", sa.Integer(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("multiple_ukrdcid")
    op.drop_table("last_run_times")
    op.drop_table("error_history")
    # ### end Alembic commands ###
